package:
  name: buteo
  version: "0.8.13"

source:
  path: ./

build:
  number: 0
  script: "$PYTHON -m pip install . --no-deps --ignore-installed -vv "
  noarch: python

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - gdal
    - numba

test:
  imports:
    - buteo

about:
  home: https://github.com/casperfibaek/buteo/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Tools for merging Geospatial Analysis and AI."
